// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

class Solution {
    public char findTheDifference(String s, String t) {
        // int[] freq = new int[26];
        // for(int i=0; i<s.length(); i++){
        //     freq[s.charAt(i) - 'a']+=1;
        // }
        // for(int i=0; i<t.length(); i++){
        //     if(freq[t.charAt(i) - 'a'] == 0){
        //         return t.charAt(i);
        //     }else if(freq[t.charAt(i) - 'a']>0){
        //         freq[t.charAt(i) - 'a']-=1;
        //     }
        // }
        char ans = 0;
        for(int i=0; i<s.length(); i++){
            ans = (char) (ans ^ s.charAt(i) ^ t.charAt(i));
        }
        return (char) (ans ^ t.charAt(t.length()-1));
    }
}
